"""
Este archivo es el frontend del API para predicir demanda de tourismo con modelo ML
"""

import streamlit as st
import requests

### Backend API
API_URL = "https://perutourismdemandprediction.onrender.com/predict"



### Setup
## Title
st.title("Tourism Demand Prediction Model")
st.write("Input details in order to predict the corresponding number of tourists")

## Months
months_list = [
    'January', 'February', 'March',
    'April', 'May', 'June', 'July',
    'August', 'September', 'October',
    'November', 'December'
]
months_map = {
    'January': 1, 
    'February': 2,
    'March': 3,
    'April': 4, 
    'May': 5, 
    'June': 6, 
    'July': 7,
    'August': 8, 
    'September': 9, 
    'October': 10,
    'November': 11, 
    'December': 12
}

## Regions
regions_list = [
    'Amazonas', 
    'Apurímac', 
    'Arequipa', 
    'Ayacucho', 
    'Cajamarca', 
    'Callao', 
    'Cusco',
    'Huancavelica', 
    'Huánuco', 
    'Ica', 
    'Junín', 
    'La Libertad', 
    'Lambayeque', 
    'Lima', 
    'Loreto', 
    'Madre de Dios', 
    'Moquegua', 
    'Pasco', 
    'Piura', 
    'Puno', 
    'San Martín', 
    'Tacna', 
    'Tumbes', 
    'Ucayali', 
    'Áncash'
]

regions_map = {
    'Amazonas': 'AMAZONAS', 'Apurímac': 'APURÃMAC', 'Arequipa': 'AREQUIPA', 'Ayacucho': 'AYACUCHO', 
    'Cajamarca': 'CAJAMARCA', 'Callao': 'CALLAO', 'Cusco': 'CUSCO', 'Huancavelica': 'HUANCAVELICA', 
    'Huánuco': 'HUÃNUCO', 'Ica': 'ICA', 'Junín': 'JUNÃN', 'La Libertad': 'LA LIBERTAD', 'Lambayeque': 'LAMBAYEQUE', 
    'Lima': 'LIMA', 'Loreto': 'LORETO', 'Madre de Dios': 'MADRE DE DIOS', 'Moquegua': 'MOQUEGUA', 
    'Pasco': 'PASCO', 'Piura': 'PIURA', 'Puno': 'PUNO', 'San Martín': 'SAN MARTÃN', 'Tacna': 'TACNA', 'Tumbes': 
    'TUMBES', 'Ucayali': 'UCAYALI', 'Áncash': 'ÃNCASH'
}


## Names
regions_to_name = {
    'AMAZONAS':['LAS CATARATAS DE GOCTA', 'SITIO ARQUEOLÓGICO DE KARAJÍA', 'SITIO ARQUEOLÓGICO REVASH', 'MUSEO DE LEYMEBAMBA', 'CAVERNA DE QUIOCTA', 'COMPLEJO ARQUEOLÓGICO DE KUÉLAP'],
    'APURÃMAC':['SANTUARIO NACIONAL DE AMPAY', 'CONJUNTO ARQUEOLÓGICO DE SAYWITE', 'MUSEO ARQUEOLÓGICO ANTROPOLÓGICO DE APURÍMAC'],
    'AREQUIPA':['MONASTERIO DE SANTA CATALINA', 'RESERVA NACIONAL DE SALINAS Y AGUADA BLANCA', 'SANTUARIO NACIONAL LAGUNAS DE MEJÍA', 'RESERVA PAISAJÍSTICA SUB CUENCA DEL COTAHUASI', 'VALLE DEL COLCA'],
    'AYACUCHO':['CENTRO ARQUEOLÓGICO INTIHUATANA', 'RESERVA NACIONAL PAMPA GALERAS BARBARA DE A´CHILLE', 'MUSEO ARQUEÓLOGICO HIPÓLITO UNANUE', 'MUSEO DE SITIO DE QUINUA', 'COMPLEJO ARQUEOLÓGICO DE WARI', 'SANTUARIO HISTÓRICO PAMPA DE AYACUCHO'],
    'CAJAMARCA':['COMPLEJO MONUMENTAL BELÉN', 'SITIO ARQUEOLÓGICO KUNTUR WASI', 'CENTRO ARQUEOLÓGICO VENTANILLAS DE OTUZCO', 'MONUMENTO ARQUEOLÓGICO CUMBEMAYO'],
    'CALLAO':['RESERVA NACIONAL SISTEMA DE ISLAS, ISLOTES Y PUNTAS GUANERAS - PALOMINO', 'MUSEO NAVAL DEL PERÚ "CAPITÁN DE NAVÍO JULIO JOSÉ ELÍAS MURGUÍA" - SEDE CALLAO', 'MUSEO DE FORTALEZA DEL REAL FELIPE'],
    'CUSCO':['EXPLANADA DE SAQSAYHUAMAN', 'MUSEO DE SITIO CHINCHERO', 'COMPLEJO ARQUEOLÓGICO DE TARAWASI', 'PARQUE ARQUEOLÓGICO DE CHOQUEQUIRAO', 'RUMIPUNKU', 'MUSEO HISTÓRICO REGIONAL - CUSCO', 'PUQRO', 'COMPLEJO ARQUEOLÓGICO DE TIPÓN', 'CAMINO INKA INTIHUATANA KM. 122', 'PARQUE ARQUEOLÓGICO DE PISAQ', 'LLAULLIPATA', 'SERVICIOS DE TREN INCA RAIL', 'CAMINO INKA PISCACUCHO (KM. 82)', 'MUSEO DE SITIO MANUEL CHÁVEZ BALLÓN', 'CAMINO INKA CHACHABAMBA (KM. 104)', 'SANTUARIO HISTÓRICO DE MACHUPICCHU', 'PARQUE ARQUEOLÓGICO DE PIKILLAQTA', 'CAMINO INKA QORYWAYRACHINA (KM. 88)', 'PARQUE ARQUEOLÓGICO DE RAQCHI', 'SITIO ARQUEOLÓGICO DE TAMBOMACHAY', 'SITIO ARQUEOLÓGICO DE PUKAPUKARA', 'COMPLEJO ARQUEOLÓGICO DE HUCHUY QOSQO', 'SAPANTIANA', 'SERVICIOS DE TRENES DE PERU RAIL', 'COMPLEJO ARQUEOLÓGICO DE MORAY', 'PARQUE ARQUEOLÓGICO DE OLLANTAYTAMBO', 'SITIO ARQUEOLÓGICO DE QENQO', 'CIUDAD INKA DE MACHUPICCHU'],
    'HUANCAVELICA':['MUSEO ARQUEOLÓGICO "SAMUEL HUMBERTO ESPINOZA LOZANO"', 'MUSEO REGIONAL "DANIEL HERNÁNDEZ MORILLO"'],
    'HUÃNUCO':['COMPLEJO ARQUEOLÓGICO HUÁNUCO PAMPA', 'PARQUE NACIONAL DE TINGO MARÍA (CUEVA DE LAS LECHUZAS)', 'COMPLEJO ARQUEOLÓGICO KOTOSH'],
    'ICA':['MUSEO DE SITIO PARACAS "JULIO C. TELLO"', 'RESERVA NACIONAL SISTEMA DE ISLAS, ISLOTES Y PUNTAS GUANERAS (RNSIIPG) SAN JUAN', 'MIRADOR DE LAS LÍNEAS DE NASCA', 'RESERVA NACIONAL SAN FERNANDO', 'RESERVA NACIONAL DE PARACAS', 'MUSEO REGIONAL ADOLFO BERMÚDEZ JENKINS', 'RESERVA NACIONAL SISTEMA DE ISLAS, ISLOTES Y PUNTAS GUANERAS (RNSIIPG) ISLAS BALLESTAS'],
    'JUNÃN':['SANTUARIO HISTÓRICO DE CHACAMARCA', 'MUSEO REGIONAL DE ARQUEOLOGÍA DE JUNÍN', 'MUSEO DE SITIO Y SANTUARIO DE WARIWILCA'],
    'LA LIBERTAD':['COMPLEJO ARQUEOLÓGICO HUACA DEL SOL Y DE LA LUNA', 'MUSEO DE SITIO CHAN CHAN', 'COMPLEJO ARQUEOLÓGICO HUACA ARCO IRIS', 'COMPLEJO ARQUEOLÓGICO HUACA EL BRUJO', 'PALACIO NIKÁN "CASA DEL CENTRO"'],
    'LAMBAYEQUE':['MUSEO DE TUMBAS REALES DEL SEÑOR DE SIPÁN', 'MUSEO NACIONAL DE ARQUEOLOGÍA Y ETNOGRAFÍA HEINRICH BRÜNING', 'MUSEO DE SITIO DE TÚCUME', 'REFUGIO DE VIDA SILVESTRE DE LAQUIPAMPA', 'MUSEO NACIONAL DE SICÁN', 'SANTUARIO HISTÓRICO BOSQUE DE PÓMAC', 'MUSEO DE SITIO HUACA RAJADA SIPÁN', 'MUSEO DE SITIO HUACA CHOTUNA-CHORNACAP'],
    'LIMA':['CIRCUITO MÁGICO DEL AGUA DEL PARQUE DE LA RESERVA', 'MUSEO NACIONAL DE LA CULTURA PERUANA', 'MUSEO DE SITIO "EL MIRADOR DEL CERRO SAN CRISTÓBAL"', 'LUGAR DE LA MEMORIA, LA TOLERANCIA Y LA INCLUSIÓN SOCIAL', 'ZONA ARQUEOLÓGICA DE HUAYCÁN DE CIENEGUILLA', 'MUSEO DE SITIO ARTURO JIMÉMEZ BORJA - PURUCHUCO', 'RESERVA PAISAJÍSTICA NOR YAUYOS - COCHAS', 'MUSEO NAVAL CASA GRAU', 'MUSEO DE LOS COMBATIENTES DEL MORRO DE ARICA', 'MUSEO DE ARTE ITALIANO', 'MUSEO DE SITIO HUALLAMARCA', 'RESERVA NACIONAL DE LACHAY', 'REFUGIO DE VIDA SILVESTRE PANTANOS DE VILLA', 'MUSEO DEL EJÉRCITO CONTEMPORÁNEO CHAVÍN DE HUÁNTAR', 'MUSEO DE SITIO ANDRÉS AVELINO CÁCERES', 'MUSEO DE SITIO PACHACAMAC', 'MUSEO DE SITIO HUACA PUCLLANA', 'COMPLEJO ARQUEOLÓGICO MATEO SALADO', 'CENTRO TURÍSTICO CASTILLO DE CHANCAY', 'MUSEO DE LA NACIÓN', 'CASA MUSEO JOSÉ CARLOS MARIÁTEGUI', 'CIUDAD SAGRADA DE CARAL', 'MUSEO NACIONAL DE ARQUEOLOGÍA'],
    'LORETO':['RESERVA NACIONAL DE PACAYA SAMIRIA', 'MUSEO AMÉRICA', 'RESERVA ALLPAHUAYO-MISHANA', 'COMPLEJO TURÍSTICO DE QUISTOCOCHA', 'ZONA RESERVADA SIERRA DIVISOR'],
    'MADRE DE DIOS':['PARQUE NACIONAL DEL MANU', 'RESERVA NACIONAL DE TAMBOPATA'],
    'MOQUEGUA':['MUSEO CONTISUYO', 'RESERVA NACIONAL DE ISLAS, ISLOTES Y PUNTAS GUANERAS-PUNTA COLES'],
    'PASCO':['PARQUE NACIONAL YANACHAGA CHEMILLÉN', 'SANTUARIO NACIONAL DE HUAYLLAY'],
    'PIURA':['ZONA ARQUEOLÓGICA Y MUSEO DE SITIO NARIHUALÁ', 'CASA MUSEO GRAN ALMIRANTE GRAU', 'SALA DE ORO DEL MUSEO MUNICIPAL'],
    'PUNO':['ISLA UROS DEL LAGO TITICACA', 'ISLA TAQUILE DEL LAGO TITICACA', 'COMPLEJO ARQUEOLÓGICO DE SILLUSTANI', 'RESERVA NACIONAL DEL TITICACA', 'COMPLEJO ARQUEOLÓGICO Y MUSEO DE PUKARÁ', 'ISLA AMANTANI DEL LAGO TITICACA', 'MUSEO TEMPLO SAN JUAN DE LETRÁN'],
    'SAN MARTÃN':['RECREO TURÍSTICO NACIENTE DE TIOYACU', 'LOS BAÑOS TERMALES DE SAN MATEO', 'CATARATA DE AHUASHIYACU', 'LAGUNA AZUL - SAUCE', 'RESERVA ECOLÓGICA TINGANA', 'CUEVA DE PALESTINA', 'AGUAJAL RENACAL RÍO ROMERO SANTA ELENA'],
    'TACNA':['MUSEO DE PEAÑAS', 'MUSEO HISTÓRICO REGIONAL - TACNA'],
    'TUMBES':['SANTUARIO NACIONAL LOS MANGLARES DE TUMBES', 'MUSEO DE SITIO CABEZA DE VACA "GRAN CHILIMASA"', 'PARQUE NACIONAL CERROS DE AMOTAPE'],
    'UCAYALI':['CATARATA SHAMBILLO', 'RECURSO TURÍSTICO VELO DE LA NOVIA', 'ZOOLÓGICO PARQUE NATURAL DE PUCALLPA', 'RECURSO TURÍSTICO DUCHA DEL DIABLO', 'RECURSO TURÍSTICO LOS TOBOGANES', 'PUENTE AGUAYTIA'],
    'ÃNCASH':['MUSEO REGIONAL DE CASMA "MAX UHLE"', 'MONUMENTO ARQUEOLÓGICO DE WILLKAWAIN', 'MONUMENTO ARQUEOLÓGICO CHAVÍN DE HUÁNTAR', 'MUSEO ARQUEOLÓGICO DE ÁNCASH', 'PARQUE NACIONAL HUASCARÁN', 'COMPLEJO ARQUEOLÓGICO DE PAÑAMARCA'],
}


### Streamlit boxes
month = st.selectbox(
    'Month',
    months_list,
    index=None,
    placeholder="Choose a month"
)


region = st.selectbox(
    "Site's Region",
    regions_list,
    index=None,
    placeholder="Choose a region"
)

if region:
    name = st.selectbox(
        "Site's Name",
        regions_to_name[regions_map[region]],
        index=None,
        placeholder="Choose a tourist site"
    )

### Prediction
if st.button('Predict Number of Tourists'):
    try:
        payload = {
            "month": months_map[month],
            "region": regions_map[region],
            "name": name
        }

        response = requests.post(
            API_URL,
            json=payload
        )

        if response.status_code == 200:
            result = response.json()
            st.success(f'Predicted Number of Tourists: {result['prediction']}')
        else:
            st.error(f'Error {response.status_code}: {response.text}')
    except requests.exceptions.RequestException as e:
        st.error(f'Cannot connect with backend: {e}')
    




